site_name: Wiki
site_description: VulWiki，漏洞库
site_author: Morker
site_url: https://wiki.96.mk/

repo_name: 'nosafer/nosafer.github.io'
repo_url: 'https://github.com/nosafer/nosafer.github.io'

theme:
  name: material
  language: 'zh'
  font: false
  palette:
    primary: 'black'
    accent: 'red'
    scheme: 'preference'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nosafer
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
